CREATE DATABASE IF NOT EXISTS blog;
CREATE DATABASE IF NOT EXISTS blog2;
USE blog;
CREATE TABLE IF NOT EXISTS roles
(
    id   INT          NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO roles(name)
VALUES ('ROLE_CUSTOMER');
INSERT INTO roles(name)
VALUES ('ROLE_ADMIN');